# -*- coding: utf-8 -*-
"""chuseok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1np6h7RPG84Vhkzt5aD_KJc48JoqPGqIf
"""

import pandas as pd
import joblib

def submission(pred_path, test_path, name):

  test = pd.read_csv(test_path)
  pred = joblib.load(pred_path)

  result = pd.concat([test['ID'],pd.Series(pred)],axis = 1)
  result.columns = (['ID','수요량'])
  result.to_csv(f'{name}.csv',index = False)

def ensemble(path1,path2,name):

  df1 = pd.read_csv('path1')
  df2 = pd.read_csv('path2')

  mean_수요량 = (df1['수요량'] + df2['수요량']) / 2
  result = pd.concat([df1['ID'],pd.Series(mean_수요량)],axis = 1)
  result.to_csv(f'{name}.csv',index = False)

def ensemble_three(path1,path2,path3,name):

  df1 = pd.read_csv('path1')
  df2 = pd.read_csv('path2')
  df3 = pd.read_csv('path3')

  mean_수요량 = (df1['수요량'] + df2['수요량'] + df3['수요량']) / 3
  result = pd.concat([df1['ID'],pd.Series(mean_수요량)],axis = 1)
  result.to_csv(f'{name}.csv',index = False)